#!/bin/zsh

#+AUTHOR: sdll
#+DATE: 17/09/2016
#+COMMENT: Please feel free to use the code for good. Happy hacking!
# ------------------------------------------------------------------------------

function assort() {
    # input:
    #       $1: type
    #       $2: file
    #       $3: destination
    new_place=$PMT_NTS/$3
    if [[ ( $2 == *.pdf ) || ( $2 == *.tex ) ]]
    then
	echo "Hurray, there is $2 for $3!";
	echo \
	    "Moving the file $2 to the $3 directory in $PMT_NTS..."
	mv $2 $new_place
    fi
    echo "Parsing the file name for publishing..."
    filename=$(basename "$2")
    new_f=$(echo ${filename%.*} | sed -r 's/[_]+/: /g' | \
		sed -r 's/[\+]+/ /g' | \
		sed -r "s/\b$1//g" | \
		sed -r 's/([0-9]-[0-9]-[0-9])-([a-zA-Z])/\1 \2/g') | \
        sed -r 's/[-]+/ /g'
    if [[ $f == *.pdf ]]
    then
	    if [ -f $NTS_TMP_LOG ]; then
	        echo "  - [[https://github.com/sdll/NOTES/blob/master/$1/$f][$new_f]] [[https://github.com/sdll/NOTES/blob/master/$1/$filename.tex][(src)]]" >> $NTS_TMP_LOG
	    else
	        echo "  - [[https://github.com/sdll/NOTES/blob/master/$1/$f][$new_f]] [[https://github.com/sdll/NOTES/blob/master/$1/$filename.tex][(src)]]" > $NTS_TMP_LOG
	    fi
    fi
    echo "Done!"
}

# -------------------------------------------------------
# Remove the debris, saving a back-up
# -------------------------------------------------------
cd $TMP_NTS
git add --all
git commit -a -m "$(date +%y%m%d): new notes"
find . -type f ! \( -path "*/.git/*" -o -name '*.tex' -o -name '*.pdf' -o -name '*.org' -o -name '*.txt' \) -delete

# -------------------------------------------------------
# Launch!
# -------------------------------------------------------

cd $PMT_NTS;

#########################################################
# d is a predefined class for the notes to be sorted into
# -------------------------------------------------------
# f is the file of the note
#########################################################

if [ -n "$(ls -A $TMP_NTS)" ]; then
    for d in *; do
        if [ -d "$d" ] && [ -n "$(ls -A $TMP_NTS)" ]; then
	    cd $TMP_NTS;
	    for f in *; do
                if [ -f "$f" ]; then
		    if [[ $(basename "$f") = *"${d}"* ]]
		    then
			assort ${d} $f $d
		    fi
		fi
	    done

	fi
	cd $PMT_NTS
    done
else
    echo "There are no new notes in $TMP_NTS."
fi

cd $PMT_NTS
git add --all
git commit -a -m "$(date +%y%m%d)"
git push origin master
