#!/bin/zsh

#+AUTHOR: sdll
#+DATE: 30/09/2016
#+COMMENT: Please feel free to use the code for good. Happy hacking!

# ------------------------------------------------------------------------------
# Remove the debris
# ------------------------------------------------------------------------------

#rm -f $NTS_TMP_LOG;

# ------------------------------------------------------------------------------
# Launch!
# ------------------------------------------------------------------------------

cd $PMT_NTS;

# d is a predefined class for the notes to be sorted into
# f is the file of the note
if [ -n "$(ls -A $TMP_SCANS)" ]; then

            cd $TMP_SCANS

            for dname in *; do


                if [ -d "$dname" ]; then

                    cd $dname
                    echo $(pwd)
                    gimp -i -b '(batch-whiteboard-clean "*.jpg")' -b '(gimp-quit 0)''"")'
                    convert  -density 300x300 -quality 7 -compress jpeg *.jpg $dname.pdf

                    for f in *; do
                    if [[ $f =~ \.pdf$ ]]; then

                            if [[ $(basename "$f") = *"${d}"* ]]
                            then
                                cp $f /home/aleph/TMP/FLS/ACC
                                mv $f $TMP_NTS/
                            else
                                echo "No scans!"
                        fi
                    fi
                    done
                    cd ..
                fi
            done
else
    echo "There are no new notes in $TMP_SCANS."
fi
cd ~/TMP/FLS/ACC/
# cd $PMT_NTS
# git add --all
# git commit -a -m "$(date +%y%m%d)"
# git push origin $(git_current_branch)
